In [31]:
from transformers import AutoTokenizer, AutoModel, BertModel, RobertaModel
import os
import sys
import pickle
import torch

import wandb
import jsonlines
import json
import pandas as pd
import spacy
import spacy_transformers

In [51]:
m = "sebastian-hofstaetter/distilbert-dot-tas_b-b256-msmarco"
m = "distilbert-base-uncased"

In [ ]:
tokenizer = AutoTokenizer.from_pretrained(m)
model = AutoModel.from_pretrained(m)

In [53]:
type(model)

transformers.models.distilbert.modeling_distilbert.DistilBertModel

In [54]:
tokenizer

PreTrainedTokenizerFast(name_or_path='distilbert-base-uncased', vocab_size=30522, model_max_len=512, is_fast=True, padding_side='right', truncation_side='right', special_tokens={'unk_token': '[UNK]', 'sep_token': '[SEP]', 'pad_token': '[PAD]', 'cls_token': '[CLS]', 'mask_token': '[MASK]'})

In [ ]:
bert = AutoModel.from_pretrained('bert-base-uncased')
bert_tokenizer = AutoTokenizer.from_pretrained('bert-base-uncased')

In [ ]:
bert_tokenizer_cased = AutoTokenizer.from_pretrained('bert-base-cased')

In [55]:
print(tokenizer("Hello how are you"))
print(tokenizer("HELLO how are you"))

{'input_ids': [101, 7592, 2129, 2024, 2017, 102], 'attention_mask': [1, 1, 1, 1, 1, 1]}
{'input_ids': [101, 7592, 2129, 2024, 2017, 102], 'attention_mask': [1, 1, 1, 1, 1, 1]}


In [49]:
print(bert_tokenizer("Hello how are you"))
print(bert_tokenizer("HELLO how are you"))

{'input_ids': [101, 7592, 2129, 2024, 2017, 102], 'token_type_ids': [0, 0, 0, 0, 0, 0], 'attention_mask': [1, 1, 1, 1, 1, 1]}
{'input_ids': [101, 7592, 2129, 2024, 2017, 102], 'token_type_ids': [0, 0, 0, 0, 0, 0], 'attention_mask': [1, 1, 1, 1, 1, 1]}


In [8]:
x["dataset"].unique()

array(['nq-train-new-complement', 'nq-train-new-gender',
       'nq-train-new-male', 'nq-train-new-female', 'msmarco-female',
       'msmarco-male', 'msmarco-neutral', 'msmarco-gender', 'all_gender'],
      dtype=object)

In [43]:
nlp = spacy.load("en_core_web_trf")

In [85]:
examples = [
"who was famous for singing i'm a small town girl?",
"who was famous for singing i'm a small town girl",
"who was famous for singing im a small town girl",
"who was famous for singing im a small town girl?",
"who was famous for singing I'm a small town girl",
"who was famous for singing I'm a small town girl?",
"who was a famous girl from a small town?",
"who sang turn back the hands of time?",
 "who is considered the mother of philippine folklore?",
"who is the lead in how i met your mother?",
"who sings the song i'll do anything for you?",
]

In [86]:
for ex in examples:
    res = nlp(ex)
    print(res)
    print([(x.dep_,x.text) for x in res if x.dep_ == "ROOT"])
    print([(x.dep_, x.text, [i for i in x.subtree], x.pos_) for x in res])
    print("\n")

who was famous for singing i'm a small town girl?
[('ROOT', 'was')]
[('nsubj', 'who', [who], 'PRON'), ('ROOT', 'was', [who, was, famous, for, singing, i, 'm, a, small, town, girl, ?], 'AUX'), ('acomp', 'famous', [famous, for, singing], 'ADJ'), ('prep', 'for', [for, singing], 'ADP'), ('pobj', 'singing', [singing], 'NOUN'), ('nsubj', 'i', [i], 'PRON'), ('parataxis', "'m", [i, 'm, a, small, town, girl, ?], 'AUX'), ('det', 'a', [a], 'DET'), ('amod', 'small', [small], 'ADJ'), ('compound', 'town', [small, town], 'NOUN'), ('attr', 'girl', [a, small, town, girl], 'NOUN'), ('punct', '?', [?], 'PUNCT')]


who was famous for singing i'm a small town girl
[('ROOT', "'m")]
[('nsubj', 'who', [who], 'PRON'), ('advcl', 'was', [who, was, famous, for, singing], 'AUX'), ('acomp', 'famous', [famous, for, singing], 'ADJ'), ('prep', 'for', [for, singing], 'ADP'), ('pobj', 'singing', [singing], 'NOUN'), ('nsubj', 'i', [i], 'PRON'), ('ROOT', "'m", [who, was, famous, for, singing, i, 'm, a, small, town, girl],

In [ ]:
# if comthing is eitehr prep or xcomp

In [27]:
dp= "/home/seraphina/contriever/beir/results/contriever/all_metrics_all_seeds_gender.pkl"

In [28]:
df = pd.read_pickle(dp)

In [36]:
df[df["data_type"] == "raw"]["compression"].unique()

array([36.39, 37.29, 37.88, 38.14, 37.79, 37.02, 37.85, 37.33, 36.85,
       36.98, 37.51, 37.64, 36.77, 37.63, 37.7 , 37.69, 37.08, 37.52,
       36.82, 37.34, 37.73])

In [22]:
with open("biasinbios_type2model2seed2compression.pkl", "rb") as fin:
    test = pickle.load(fin)

In [23]:
test

{'scrubbed': defaultdict(dict,
             {'contriever-msmarco': {'seed_42': 1.78},
              'contriever': {'seed_13': 1.79,
               'seed_12': 1.8,
               'seed_11': 1.78,
               'seed_10': 1.79,
               'seed_9': 1.8,
               'seed_1': 1.8,
               'seed_16': 1.79,
               'seed_14': 1.79,
               'seed_0': 1.8,
               'seed_5': 1.8,
               'seed_7': 1.77,
               'seed_4': 1.8,
               'seed_2': 1.8,
               'seed_8': 1.79,
               'seed_6': 1.8},
              'bert': {'seed_8': 1.69,
               'seed_0': 1.69,
               'seed_4': 1.65,
               'seed_13': 1.65,
               'seed_6': 1.66,
               'seed_11': 1.67,
               'seed_5': 1.65,
               'seed_7': 1.65,
               'seed_10': 1.67,
               'seed_14': 1.69,
               'seed_9': 1.66,
               'seed_2': 1.68,
               'seed_16': 1.67,
               'seed

In [203]:
wiki = "tmp.jsonl"
with jsonlines.open(wiki) as reader:
    for i, entry in enumerate(reader):
        print(entry)
        print("----")
        if i==10:
            break

{'dialog': [[{'text': 'Ashok Lavasa', 'name': 'Ashok Lavasa', 'label_candidates': ['ABOUT:gender-neutral', 'ABOUT:female', 'ABOUT:male', 'ABOUT:non-binary'], 'episode_done': True, 'id': 'md_gender:wikipedia', 'eval_labels': ['ABOUT:male']}, {'id': 'RepeatLabelAgent', 'text': 'ABOUT:male', 'episode_done': False, 'metrics': {'exs': 1, 'accuracy': 1.0, 'precision': 1.0, 'recall': 1.0, 'f1': 1.0, 'bleu-4': 1.0000000000000004e-06}}]], 'context': [], 'metadata_path': 'tmp.metadata'}
----
{'dialog': [[{'text': 'Ashok Lavasa (IAST: "Aśoka Lavāsā") (born 21 October 1957) is a retired 1980 batch IAS officer of Haryana cadre and is one of the two Election Commissioners of India. He has also served as the Finance Secretary of India, Environment, Forests and Climate Change Secretary of India and Civil Aviation Secretary of India.', 'name': 'Ashok Lavasa', 'label_candidates': ['ABOUT:gender-neutral', 'ABOUT:female', 'ABOUT:male', 'ABOUT:non-binary'], 'episode_done': True, 'id': 'md_gender:wikipedia'

In [201]:
data

{'dialog': [[{'text': 'Ashok Lavasa',
    'name': 'Ashok Lavasa',
    'label_candidates': ['ABOUT:gender-neutral',
     'ABOUT:female',
     'ABOUT:male',
     'ABOUT:non-binary'],
    'episode_done': True,
    'id': 'md_gender:wikipedia',
    'eval_labels': ['ABOUT:male']},
   {'id': 'RepeatLabelAgent',
    'text': 'ABOUT:male',
    'episode_done': False,
    'metrics': {'exs': 1,
     'accuracy': 1.0,
     'precision': 1.0,
     'recall': 1.0,
     'f1': 1.0,
     'bleu-4': 1.0000000000000004e-06}}]],
 'context': [],
 'metadata_path': 'tmp.metadata'}

In [200]:
with open("results/type2model2seed2compression.pkl", "rb") as fin:
            m2s2c = pickle.load(fin)

In [181]:
m2s2c
#["contriever"]

{'raw': defaultdict(dict,
             {'bert': {'seed_9': 32.68,
               'seed_14': 33.14,
               'seed_10': 32.73,
               'seed_12': 32.64,
               'seed_13': 33.31,
               'seed_11': 30.62,
               'seed_8': 31.12,
               'seed_6': 30.22,
               'seed_5': 31.71,
               'seed_4': 32.89,
               'seed_2': 31.85,
               'seed_0': 31.43,
               'seed_7': 25.11,
               'seed_16': 32.69,
               'seed_1': 32.2},
              'contriever': {'seed_16': 36.77,
               'seed_14': 37.64,
               'seed_13': 37.72,
               'seed_0': 36.39,
               'seed_12': 37.51,
               'seed_11': 36.98,
               'seed_9': 37.33,
               'seed_8': 37.85,
               'seed_10': 36.85,
               'seed_7': 37.02,
               'seed_5': 38.14,
               'seed_6': 37.79,
               'seed_4': 37.88,
               'seed_1': 36.82,
            

In [182]:
### fix wandb
project_name="seraphinatarrant/Bias in Bios MDL probing"
api = wandb.Api()
# Project is specified by <entity/project-name>
runs = api.runs(project_name)


In [152]:
for run in runs:
    if run.config["model"] == "bert":
        #print("yes")
        run.config["model_subtype"] = run.config["model"]
        run.update()

In [155]:
for run in runs:
    if "architecture" in run.config:
        del run.config["architecture"]
        run.update()

In [192]:
for run in runs:
    if run.name == "major-water-12":
        run.config["seed"] = 42
        run.config["model_seed"] = 42
        run.update()


In [64]:
test = torch.rand(393423, 768)

In [66]:
test[393000:393300, :]

tensor([[0.0340, 0.1019, 0.4120,  ..., 0.8725, 0.3032, 0.1334],
        [0.3287, 0.0562, 0.6702,  ..., 0.3756, 0.8273, 0.2865],
        [0.0790, 0.8859, 0.3092,  ..., 0.7342, 0.3595, 0.6041],
        ...,
        [0.9530, 0.3197, 0.1757,  ..., 0.6333, 0.2717, 0.2646],
        [0.2507, 0.2747, 0.0665,  ..., 0.4058, 0.9625, 0.5300],
        [0.7284, 0.9791, 0.0971,  ..., 0.4099, 0.7184, 0.1446]])

In [2]:
bios_dir = "data/biasbios/"

In [161]:
bsd = torch.load("data/biasbios/dev.tokens_scrubbed_bert.pt")

In [162]:
bd = torch.load("data/biasbios/dev.tokens_raw_bert.pt")

In [163]:
bsd

{'X': {'input_ids': tensor([[ 101, 2852, 1012,  ...,    0,    0,    0],
         [ 101, 1035, 2470,  ...,    0,    0,    0],
         [ 101, 1035, 2038,  ...,    0,    0,    0],
         ...,
         [ 101, 1035, 2318,  ...,    0,    0,    0],
         [ 101, 1035, 3322,  ...,    0,    0,    0],
         [ 101, 1035, 2038,  ...,    0,    0,    0]]), 'token_type_ids': tensor([[0, 0, 0,  ..., 0, 0, 0],
         [0, 0, 0,  ..., 0, 0, 0],
         [0, 0, 0,  ..., 0, 0, 0],
         ...,
         [0, 0, 0,  ..., 0, 0, 0],
         [0, 0, 0,  ..., 0, 0, 0],
         [0, 0, 0,  ..., 0, 0, 0]]), 'attention_mask': tensor([[1, 1, 1,  ..., 0, 0, 0],
         [1, 1, 1,  ..., 0, 0, 0],
         [1, 1, 1,  ..., 0, 0, 0],
         ...,
         [1, 1, 1,  ..., 0, 0, 0],
         [1, 1, 1,  ..., 0, 0, 0],
         [1, 1, 1,  ..., 0, 0, 0]])},
 'masks': tensor([[1, 1, 1,  ..., 0, 0, 0],
         [1, 1, 1,  ..., 0, 0, 0],
         [1, 1, 1,  ..., 0, 0, 0],
         ...,
         [1, 1, 1,  ..., 0, 0, 0

In [164]:
bd

{'X': {'input_ids': tensor([[ 101, 2852, 1012,  ...,    0,    0,    0],
         [ 101, 2010, 2470,  ...,    0,    0,    0],
         [ 101, 2016, 2038,  ...,    0,    0,    0],
         ...,
         [ 101, 9553, 2318,  ...,    0,    0,    0],
         [ 101, 2016, 3322,  ...,    0,    0,    0],
         [ 101, 2016, 2038,  ...,    0,    0,    0]]), 'token_type_ids': tensor([[0, 0, 0,  ..., 0, 0, 0],
         [0, 0, 0,  ..., 0, 0, 0],
         [0, 0, 0,  ..., 0, 0, 0],
         ...,
         [0, 0, 0,  ..., 0, 0, 0],
         [0, 0, 0,  ..., 0, 0, 0],
         [0, 0, 0,  ..., 0, 0, 0]]), 'attention_mask': tensor([[1, 1, 1,  ..., 0, 0, 0],
         [1, 1, 1,  ..., 0, 0, 0],
         [1, 1, 1,  ..., 0, 0, 0],
         ...,
         [1, 1, 1,  ..., 0, 0, 0],
         [1, 1, 1,  ..., 0, 0, 0],
         [1, 1, 1,  ..., 0, 0, 0]])},
 'masks': tensor([[1, 1, 1,  ..., 0, 0, 0],
         [1, 1, 1,  ..., 0, 0, 0],
         [1, 1, 1,  ..., 0, 0, 0],
         ...,
         [1, 1, 1,  ..., 0, 0, 0

In [13]:
mylist=[]
count = 0
for x in ["train", "dev", "test"]:
    with open(os.path.join(bios_dir, f"{x}.pickle"), "rb") as fin:
        data = pickle.load(fin)
        print(len(data))
        count += len(data)
        mylist.extend(data)

255710
39369
98344


In [17]:
mylist[100]

{'g': 'm',
 'p': 'professor',
 'text': 'Presenter: Ivan V. Korendovych, PhD, is an Assistant Professor in the Department of Chemistry at Syracuse University. Dr. Korendovych received his PhD from Tufts University for his work on oxygen activation. He then moved on to the University of Pennsylvania Medical School where he developed small protein catalysts. Since 2011, he has taught at Syracuse University. His current research interests are focused on discovery of antimicrobial drugs as well as creating biosensors for metals. Dr. Korendovych is a recipient of the 2007 Young Investigator Award from the American Chemical Society in Inorganic Chemistry.',
 'start': 117,
 'hard_text': 'Dr. Korendovych received his PhD from Tufts University for his work on oxygen activation . He then moved on to the University of Pennsylvania Medical School where he developed small protein catalysts . Since 2011 , he has taught at Syracuse University . His current research interests are focused on discovery o

In [19]:
mylist[100]['text'][:mylist[100]['start']]

'Presenter: Ivan V. Korendovych, PhD, is an Assistant Professor in the Department of Chemistry at Syracuse University.'

In [15]:
with open(os.path.join(bios_dir,"BIOS.pkl"), "wb") as fout:
    pickle.dump(mylist, fout) 

In [7]:
from contriever.src.contriever import Contriever

In [5]:
from transformers import AutoTokenizer

In [6]:
contriever = Contriever.from_pretrained("facebook/contriever") 
contriever_msmarco = Contriever.from_pretrained("facebook/contriever-msmarco")
mcontriever = Contriever.from_pretrained("facebook/mcontriever")
mcontriever_msmarco = Contriever.from_pretrained("facebook/mcontriever-msmarco")

Some weights of the model checkpoint at facebook/contriever were not used when initializing Contriever: ['pooler.dense.bias', 'pooler.dense.weight']
- This IS expected if you are initializing Contriever from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing Contriever from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Some weights of the model checkpoint at facebook/contriever-msmarco were not used when initializing Contriever: ['pooler.dense.bias', 'pooler.dense.weight']
- This IS expected if you are initializing Contriever from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS 

In [34]:
from datasets import load_dataset

In [35]:
dataset_names = ["funpedia", "new_data", "image_chat", "wizard", "convai2_inferred", "light_inferred", "opensubtitles_inferred"]
parl_dataset = "md_gender:wikipedia"

In [ ]:
for name in dataset_names:
    this_data = load_dataset("md_gender_bias", name)
    count = 0
    for x in this_data:
        count += this_data[x].num_rows
    print(f"{name}: {count}")

In [ ]:
this_data = load_dataset("md_gender_bias", "new_data")

In [49]:
set([i[0] for i in this_data["train"]['labels']])

{0, 1, 2, 3, 4, 5}

In [58]:
this_data["train"][:10]

{'text': ['He designed monumental Lovissa War Cemetery in 1920.',
  'She works as a volunteer firefighter.',
  'She participated in the FIVB volleyball grand champions cup in 2001.',
  'Correct ! Walter Havighurst was an author of many books. He loved the book Annie Oakley of the Wild West.',
  'Yes, she released only one album with them, "wołanie o słońce nad światem"',
  'i played a lot with my male friends',
  'i am a man and i do construction',
  'i am a man who loves veggies too',
  "no i'm too feminine to watch football",
  'you take the abbie sawyer to there man'],
 'original': [' She designed monumental Loviisa war cemetery in 1920',
  'I work as a volunteer firefighter.',
  'She participated in the FIVB volleyball grand champions cup in 2001',
  'Correct! Walter Havighurst was an author of many books. I loved the book Annie Oakley of the Wild West.',
  'yes, He released only one album with them, "Wołanie o słońce nad światem"',
  'I played when I was younger. What do you do?',

In [50]:
import tarfile

In [55]:
parlpath = "data/md_gender/data_to_release/new_data/data.jsonl"

In [54]:
import json

In [56]:
with open(parlpath, 'r') as fin:
    d = json.load(fin)

JSONDecodeError: Extra data: line 2 column 1 (char 253)

In [33]:
import torch
from tqdm import tqdm
from transformers i
from contriever.src.contriever import Contriever

In [39]:
data_path = "data/biasbios/tokens_raw_contriever_batch.pt"

data = torch.load(data_path)

In [22]:
roberta_data = torch.load("data/biasbios/tokens_raw_roberta-base_128.pt")

In [23]:
data['X'].shape
roberta_data["X"].shape

(393423, 128)

In [40]:
input_data = data["X"]

In [24]:
input_data[0:30,:].shape

(30, 512)

In [27]:
input_data[0].shape

(512,)

In [28]:
X = torch.tensor(data['X']).to("cuda")

In [30]:
attn = torch.tensor(data['masks']).to("cuda")

/tmp/ipykernel_1703629/198053703.py:1: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  attn = torch.tensor(data['masks']).to("cuda")


In [63]:
len(data['y'])

393423

In [41]:
for key in input_data:
    input_data[key] = input_data[key].to("cuda")
    input_data[key].requires_grad = False

In [102]:
from transformers import AutoModel
import numpy as np

In [116]:
model_version = "bert-base-uncased"
model = AutoModel.from_pretrained(model_version)

Some weights of the model checkpoint at bert-base-uncased were not used when initializing BertModel: ['cls.predictions.transform.dense.bias', 'cls.predictions.transform.LayerNorm.weight', 'cls.seq_relationship.weight', 'cls.seq_relationship.bias', 'cls.predictions.transform.LayerNorm.bias', 'cls.predictions.bias', 'cls.predictions.transform.dense.weight', 'cls.predictions.decoder.weight']
- This IS expected if you are initializing BertModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).


In [204]:
""" Implementation of OKapi BM25 with sklearn's TfidfVectorizer
Distributed as CC-0 (https://creativecommons.org/publicdomain/zero/1.0/)
"""

import numpy as np
from sklearn.feature_extraction.text import TfidfVectorizer
from scipy import sparse


class BM25(object):
    def __init__(self, b=0.75, k1=1.6):
        self.vectorizer = TfidfVectorizer(norm=None, smooth_idf=False)
        self.b = b
        self.k1 = k1

    def fit(self, X):
        """ Fit IDF to documents X """
        self.vectorizer.fit(X)
        y = super(TfidfVectorizer, self.vectorizer).transform(X)
        self.avdl = y.sum(1).mean()

    def transform(self, q, X):
        """ Calculate BM25 between query q and documents X """
        b, k1, avdl = self.b, self.k1, self.avdl

        # apply CountVectorizer
        X = super(TfidfVectorizer, self.vectorizer).transform(X)
        len_X = X.sum(1).A1
        q, = super(TfidfVectorizer, self.vectorizer).transform([q])
        assert sparse.isspmatrix_csr(q)

        # convert to csc for better column slicing
        X = X.tocsc()[:, q.indices]
        denom = X + (k1 * (1 - b + b * len_X / avdl))[:, None]
        # idf(t) = log [ n / df(t) ] + 1 in sklearn, so it need to be coneverted
        # to idf(t) = log [ n / df(t) ] with minus 1
        idf = self.vectorizer._tfidf.idf_[None, q.indices] - 1.
        numer = X.multiply(np.broadcast_to(idf, X.shape)) * (k1 + 1)                                                          
        return (numer / denom).sum(1).A1

In [218]:
texts[0]

"From: lerxst@wam.umd.edu (where's my thing)\nSubject: WHAT car is this!?\nNntp-Posting-Host: rac3.wam.umd.edu\nOrganization: University of Maryland, College Park\nLines: 15\n\n I was wondering if anyone out there could enlighten me on this car I saw\nthe other day. It was a 2-door sports car, looked to be from the late 60s/\nearly 70s. It was called a Bricklin. The doors were really small. In addition,\nthe front bumper was separate from the rest of the body. This is \nall I know. If anyone can tellme a model name, engine specs, years\nof production, where this car is made, history, or whatever info you\nhave on this funky looking car, please e-mail.\n\nThanks,\n- IL\n   ---- brought to you by your neighborhood Lerxst ----\n\n\n\n\n"

In [286]:
from scipy.sparse._csr import csr_matrix

In [287]:
type(v) == csr_matrix

True

In [207]:
x = bm25.transform(texts[0], texts)

In [225]:
v = bm25.vectorizer.transform(texts)

In [234]:
row_idx, col_idx = v.nonzero()

In [251]:
v.indptr

array([      0,      89,     182, ..., 1787372, 1787496, 1787565],
      dtype=int32)

In [253]:
v2 = torch.sparse_csr_tensor(v.indptr, col_idx, v.data)

/tmp/ipykernel_1769822/3529406853.py:1: UserWarning: Sparse CSR tensor support is in beta state. If you miss a functionality in the sparse tensor support, please submit a feature request to https://github.com/pytorch/pytorch/issues. (Triggered internally at  ../aten/src/ATen/SparseCsrTensorImpl.cpp:68.)
  v2 = torch.sparse_csr_tensor(v.indptr, col_idx, v.data)


In [277]:
v[10].data

array([ 1.96154037,  4.44206357,  3.14996236,  2.09781706,  1.92409981,
        2.635225  ,  2.87149285,  2.72087676,  2.98512025, 10.02139561,
        7.84880114,  7.28918535,  2.21715466,  4.41212937,  3.84909068,
        4.42562485,  1.91699813,  2.58913798,  6.41441184,  2.8778311 ,
        4.05144104,  1.        ,  6.11420008,  5.08668371,  5.85637097,
        5.86779967,  4.63997565, 12.76492813,  7.24266533,  1.37234173,
        8.72426987,  7.00150328,  2.89591266,  5.92698854,  5.32307249,
        6.44423668,  1.04031386,  7.48681348,  6.89972058,  3.71630481,
        2.32168955,  4.47591107, 11.10916859,  2.26946349,  4.10322634,
        4.30062156,  2.74336084,  6.96641196,  2.26687247,  4.62328077,
        2.06497595,  2.83207333,  8.13648321, 13.44557975,  3.20360928,
        1.00327593,  3.63790887,  2.146965  ,  7.50049444,  7.24266533,
        3.47514275,  8.25426624,  2.66127523,  1.27477187, 34.16779327,
        3.53353772,  2.30167247,  8.38779764,  1.52518917,  3.59

In [283]:
v2[10].data

tensor(indices=tensor([[125110, 125095, 124616, 124332, 123984, 123759, 123196,
                        121265, 119714, 117230, 116882, 116139, 115475, 114702,
                        114646, 114586, 114579, 114520, 114455, 114428, 111695,
                        111322, 110130, 108718, 106965, 104702, 103528, 101898,
                        100059,  99721,  98828,  94986,  94362,  91722,  91192,
                         90774,  90379,  90364,  90266,  90097,  89919,  89860,
                         89550,  89362,  87170,  85447,  84681,  83914,  83706,
                         83256,  80638,  80005,  79785,  76681,  76377,  76032,
                         76007,  75901,  75033,  75028,  72384,  69511,  68766,
                         68532,  68524,  66670,  64186,  63910,  62221,  61959,
                         60731,  59534,  58830,  56979,  55597,  54163,  53441,
                         51268,  49331,  49328,  48421,  47982,  41633,  40647,
                         40477,  37423, 

In [110]:
model="bert"
train_tok=f"data/biasbios/train.tokens_raw_{model}.pt"
dev_tok=f"data/biasbios/dev.tokens_raw_{model}.pt"
test_tok=f"data/biasbios/test.tokens_raw_{model}.pt"

In [343]:
ds1 = torch.load("test.pt")

In [329]:
ds.tensors[0].shape

torch.Size([300000, 512])

In [379]:
from torch.utils.data import ConcatDataset, DataLoader

In [311]:
ds = TensorDataset(data["X"]["input_ids"].int(), torch.tensor(data["X"]["attention_mask"]).char(), data['z'])


/tmp/ipykernel_1769822/941439938.py:1: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  ds = TensorDataset(data["X"]["input_ids"].int(), torch.tensor(data["X"]["attention_mask"]).char(), data['z'])


In [385]:
ds.tensors

(tensor([[  101,  2002,  2001,  ...,     0,     0,     0],
         [  101,  8840, 14226,  ...,     0,     0,     0],
         [  101, 18553, 12819,  ...,     0,     0,     0],
         ...,
         [  101,  1062,  7140,  ...,     0,     0,     0],
         [  101,  1000,  1052,  ...,     0,     0,     0],
         [  101,  2016,  2351,  ...,     0,     0,     0]], dtype=torch.int32),
 tensor([[1, 1, 1,  ..., 0, 0, 0],
         [1, 1, 1,  ..., 0, 0, 0],
         [1, 1, 1,  ..., 0, 0, 0],
         ...,
         [1, 1, 1,  ..., 0, 0, 0],
         [1, 1, 1,  ..., 0, 0, 0],
         [1, 1, 1,  ..., 0, 0, 0]], dtype=torch.int8),
 tensor([0, 0, 0,  ..., 1, 0, 1], dtype=torch.int8))

In [344]:
all_ds

In [345]:
for i in tqdm(range(1,4)):
    data = torch.load(f"data/md_gender/wikipedia/dev.tokens_raw_bert.pt.{i}")
    all_ds.append(TensorDataset(data["X"]["input_ids"].int(), data["X"]["attention_mask"].char(), torch.tensor(data['z']).char()))

100%|███████████████████████████████████████████████████████████████████████████████████████████████████████| 3/3 [02:05<00:00, 41.99s/it]


In [347]:
torch.save(ConcatDataset(all_ds), "data/md_gender/wikipedia/dev.tokens_raw_bert.pt.all",)

In [382]:
ds_test = torch.load("data/md_gender/wikipedia/archive/dev.tokens_raw_bert.pt.all")

In [383]:
type(ds_test)

torch.utils.data.dataset.ConcatDataset

In [389]:
t = torch.load("data/md_gender/wikipedia/vectors_extracted_from_trained_models/contriever/seed_0/0.train.vectors_raw_contriever_new.pt")

In [401]:
_counter = Counter([i.item() for i in t.tensors[1]])

In [413]:
"\n".join([f"{key}: {val/650000*100}%" for key, val in _counter.items()])

'0: 78.744%\n2: 8.179230769230768%\n1: 13.07230769230769%\n3: 0.004461538461538462%'

In [378]:
set(x.item() for x in d.datasets[0].tensors[2].unique())

{0, 1, 2, 3}

In [422]:
t.tensors[0].dtype

torch.float32

In [112]:
input_data = data['X']
vectors = []
labels = []
genders = []

y = data['y']
z = data['z']

In [99]:
bert_lengths = [torch.count_nonzero(i).item() for i in input_data["attention_mask"]]

In [107]:
contriever_lengths == bert_lengths

True

In [45]:
num_samples = len(input_data["input_ids"])
            # for key in input_data:
            #     input_data[key] = input_data[key].to(device)
start_idx = 0
vectors = []
device = "cuda"

In [121]:
device="cuda:1"

In [122]:
start_idx, last_idx = 0, 10
with torch.no_grad():
    input_ids = input_data["input_ids"][start_idx:last_idx,:].to(device)
    attns = input_data["attention_mask"][start_idx:last_idx,:].to(device)
    v = model(input_ids, attention_mask=attns)
    

In [131]:
v = v.last_hidden_state.cpu().detach()

In [138]:
vcat = torch.cat([v,v],dim=0)
vcat[0] == vcat[10]


tensor([[True, True, True,  ..., True, True, True],
        [True, True, True,  ..., True, True, True],
        [True, True, True,  ..., True, True, True],
        ...,
        [True, True, True,  ..., True, True, True],
        [True, True, True,  ..., True, True, True],
        [True, True, True,  ..., True, True, True]])

In [137]:
vcat[10]

tensor([[-0.4252,  0.1884, -0.0299,  ...,  0.4893,  0.5312,  0.3602],
        [-1.0323,  0.5132, -0.4543,  ...,  0.5786,  1.0955, -0.5138],
        [-0.8278, -0.0589, -0.1802,  ...,  1.3841,  0.8857, -1.5629],
        ...,
        [ 0.4036, -0.2770,  0.5035,  ...,  0.0131, -0.1179,  0.1435],
        [ 0.2341,  0.0206,  0.5684,  ..., -0.0109, -0.1405,  0.2937],
        [ 0.2289, -0.0943,  0.4422,  ..., -0.0665, -0.0431,  0.4522]])

In [74]:
x = torch.zeros(30,768)
y = torch.zeros(2,768)

In [84]:
torch.cat([x,y], dim=0).shape

torch.Size([32, 768])

In [414]:
#e = model(**input_data) 

In [1]:
r_path = "data/winobias/extracted_vectors/roberta-base/basic/vectors_roberta-base.pt"

In [29]:
from torch.utils.data import TensorDataset

In [3]:
import torch
v = torch.load(r_path)

False

In [5]:
v.keys()

dict_keys(['X', 'z', 'original index', 'professions'])

In [6]:
from datasets import Dataset

In [10]:
v_bb = torch.load("data/biasbios/vectors_extracted_from_trained_models/contriever/seed_0/dev.vectors_raw_contriever.pt")

In [11]:
v_bb

{'X': tensor([[-0.0306, -0.0315, -0.0677,  ..., -0.0769, -0.0994, -0.0369],
         [ 0.0063,  0.0169,  0.0437,  ..., -0.0168, -0.0927, -0.0098],
         [ 0.0692, -0.0162,  0.0102,  ...,  0.0428, -0.0485, -0.0188],
         ...,
         [-0.0582, -0.0377, -0.0446,  ..., -0.0389,  0.0487, -0.0472],
         [ 0.0445, -0.0442, -0.0356,  ...,  0.0107, -0.0374, -0.0134],
         [ 0.0081,  0.0008, -0.0028,  ...,  0.0191, -0.0443, -0.0282]],
        device='cuda:0'),
 'y': array(['Joel E. Holman, MD is a practicing Orthopedic Surgeon in Nephi, UT.',
        'Jordache A. Ellapen is an Assistant Professor of Feminist Studies in Culture and Media in the Women and Gender Studies Program in the Department of Historical Studies at UTM and holds a graduate appointment in the Women & Gender Studies Institute.',
        'Julia Lauter is an independent journalist based in Hamburg.', ...,
        'Troy Goodall is a talented photographer from New Zealand who came up with a pretty unique idea.',
  

In [12]:
str2int = {'f': 1, 'm': 0}

In [24]:
map(str2int,v_bb['z'])['z']

TypeError: 'map' object is not subscriptable

In [27]:
def preprocess_probing_data(X, z):
    z[z == 'f'] = 1
    z[z == 'm'] = 0
    z = z.astype(int)
    X, z = X, torch.tensor(z).long()

    return TensorDataset(X, z)


In [30]:
xx = preprocess_probing_data(v_bb['X'], v_bb['z'])

In [416]:
xx.tensors

(tensor([[-0.0306, -0.0315, -0.0677,  ..., -0.0769, -0.0994, -0.0369],
         [ 0.0063,  0.0169,  0.0437,  ..., -0.0168, -0.0927, -0.0098],
         [ 0.0692, -0.0162,  0.0102,  ...,  0.0428, -0.0485, -0.0188],
         ...,
         [-0.0582, -0.0377, -0.0446,  ..., -0.0389,  0.0487, -0.0472],
         [ 0.0445, -0.0442, -0.0356,  ...,  0.0107, -0.0374, -0.0134],
         [ 0.0081,  0.0008, -0.0028,  ...,  0.0191, -0.0443, -0.0282]],
        device='cuda:0'),
 tensor([0, 0, 1,  ..., 0, 1, 1]))